server:
  port: 8082

spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: mongodb+srv://incetutku:y8matr1mKb5eK1xA@user-data.6193mqx.mongodb.net/?retryWrites=true&w=majority&appName=user-data
      username: tutku
      password: s3cr3t
      database: userDB

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always

  info:
    env:
      enabled: true

info:
  app:
    name: ecom-application
    description: E-commerce App built by us
    version: 1.0.0