server:
  port: 8083

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://ep-floral-smoke-a2nicy1h-pooler.eu-central-1.aws.neon.tech/orderDB?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_sC5T9vbWNVLo
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always

  info:
    env:
      enabled: true

info:
  app:
    name: order-service
    description: Order Service App built by us
    version: 1.0.0