server:
  port: 8082

spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: ${MONGO_DB_URI}
      username: ${MONGO_DB_USERNAME}
      password: ${MONGO_DB_PASSWORD}
      database: ${MONGO_DB_DATABASE}

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always

  info:
    env:
      enabled: true

info:
  app:
    name: ecom-application
    description: E-commerce App built by us
    version: 1.0.0